excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods

disabled_rules:
- vertical_whitespace
- trailing_newline
- line_length
- unused_optional_binding
- trailing_whitespace

custom_rules:
    logging_data:
        name: "Free Logging"
        regex: 'try\? Data\(contentsOf:'
        message: "Use init?(contentsOf url: URL, logTag: String? = nil, additionalProperties: [String: Encodable] = [:]) instead."
        severity: warning
        
    logging_decompress:
        name: "Free Logging"
        regex: '\.decompressed\(using:'
        message: "Use decompressAndLog() instead."
        severity: warning
        
    logging_decode:
        name: "Free Logging"
        regex: '\.decode\('
        message: "Use decodeAndLog() instead."
        severity: warning
        
    logging_json_data:
        name: "Free Logging"
        regex: '\.data\(withJSONObject:'
        message: "Use dataAndLog() instead."
        severity: warning
            
    logging_json_object:
        name: "Free Logging"
        regex: '\.jsonObject\(with:'
        message: "Use jsonObjectAndLog() instead."
        severity: warning
    
    logging_json_encode:
        name: "Free Logging"
        regex: '\.encode\('
        message: "Use encodeAndLog() instead."
        severity: warning

    logging_regex:
        name: "Free Logging"
        regex: 'NSRegularExpression\(pattern:'
        message: "Use createAndLog() instead."
        severity: warning
